### ISSUE TITLE
NameError: name 'List' is not defined

### ISSUE THREAD

**Issue by shef4793** [goru001/nlp-for-marathi#3]
![image](https://user-images.githubusercontent.com/14148218/64486695-d89d1a00-d24d-11e9-8120-f777caa285ce.png)

I am getting an error when I'm trying to deploy the model on flask.
I didn't get an error on google colab.

**Comment by goru001** [comment]
Did you do:`from typing import List` ?

**Comment by goru001** [comment]
Closing this issue for now. Feel free to reopen if there's anything.
